#page title
page_title                                : Amigo - AI Expense Manager

# App Info
ios_app_id                                : 6450652473
ios_app_country                           : us

appstore_link                             : https://apps.apple.com/in/app/inout-expense-manager/id6450652473
playstore_link                            :
presskit_download_link                    :

app_icon                                  : assets/appicon.png
app_name                                  : Amigo - AI Expense Manager
app_price                                 :
app_description                           : Take charge of your finances with Amigo - AI Expense Manager, your ultimate companion in personal expense tracking and budget management.

enable_smart_app_banner                   : true

excerpt_separator: ""

# Information About Yourself
your_name                                 : ♥
your_link                                 : https://www.tirupatibalan.com
your_city                                 :
email_address                             : tirupati.balan@gmail.com
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           : tirupati17
youtube_username                          :
mastodon_link                             :

include: [".well-known"]

features:

  - title: Amigo, Your AI Friend
    description: Meet Amigo, your personal AI assistant in Amigo - AI Expense Manager. Amigo is more than just software; it's a companion that understands your financial habits and offers personalized advice, making finance management feel like a conversation with a friend.
    fontawesome_icon_name: user-friends

  - title: Seamless Statement Imports
    description: Importing bank statements into Amigo - AI Expense Manager is a breeze. With just a few taps, you can upload your financial statements, and Amigo will help categorize and analyze your transactions, making it easier to keep track of your finances.
    fontawesome_icon_name: file-import
    
  - title: Intuitive Navigation
    description: Effortlessly navigate your finances with a sleek and straightforward interface designed for everyday use.
    fontawesome_icon_name: compass

  - title: iCloud Integration
    description: Enjoy peace of mind with iCloud, ensuring your financial data is encrypted, backed up, and accessible only by you, with added security layers like Face ID and Touch ID.
    fontawesome_icon_name: cloud

  - title: Smart Insights
    description: Dive into your financial habits with detailed analytics and visualizations, helping you understand where your money goes and how to save more.
    fontawesome_icon_name: chart-pie

  - title: Simplified Tracking
    description: Organize your expenses and incomes with customizable categories and tags, making it easier to keep track of your financial landscape.
    fontawesome_icon_name: folder-open

  - title: Quick Find
    description: Instantly find any transaction with a robust search feature, allowing you to search by names, notes, and even hashtags.
    fontawesome_icon_name: search-plus

  - title: Worldwide Access
    description: Use Amigo - AI Expense Manager anywhere in the world, with support for local currencies and regional settings for global compatibility.
    fontawesome_icon_name: globe-americas

  - title: Device Harmony
    description: Experience your financial data in sync across all your devices, thanks to secure iCloud synchronization.
    fontawesome_icon_name: sync-alt

  - title: Privacy First
    description: Guard your financial data with biometric security options like Face ID, Touch ID, and Keychain Passcode, keeping your information for your eyes only.
    fontawesome_icon_name: user-shield

  - title: Transaction Narratives
    description: Add depth to your transactions with photos, locations, and rich links, crafting a detailed financial story.
    fontawesome_icon_name: file-image

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#000000"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.0

device_color                              : black

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#000000"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - any_additional_item

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
