#page title
page_title                                : InOut - Expense Manager                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6450652473                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : www.apps.apple.com/in/app/inout-expense-manager/id6450652473                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : InOut - Expense Manager                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Take charge of your finances with InOut - Expense Manager, your ultimate companion in personal expense tracking and budget management.


enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Tirupati Balan
your_link                                 : www.tirupatibalan.com
your_city                                 : Mumbai
email_address                             : tirupati.balan@gmail.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          :
github_username                           : tirupati17
youtube_username                          :
mastodon_link                             :



features:

  - title: Intuitive Interface
    description: Seamlessly track and manage your daily transactions with an intuitive and user-friendly interface.
    fontawesome_icon_name: magic
    
  - title: Secure Data Storage
    description: Your financial data is securely stored on Apple servers using iCloud, with advanced security features like Keychain, Face ID, and Touch ID.
    fontawesome_icon_name: shield-alt

  - title: Insightful Analytics
    description: Gain valuable insights through advanced analytics and visual reports, providing a clear snapshot of your income and expenses.
    fontawesome_icon_name: chart-bar

  - title: Cutting-edge Compatibility
    description: Stay ahead of the curve with updates for the latest iOS versions and take advantage of Swift UI 3.0.
    fontawesome_icon_name: sync

  - title: Effortless Organization
    description: Categorize and tag your transactions with ease, creating a personalized system that simplifies your financial record-keeping.
    fontawesome_icon_name: tags
  
  - title: Powerful Search
    description: Locate specific transactions effortlessly through powerful search functionality by name, notes, or hashtags.
    fontawesome_icon_name: search

  - title: Global Usability
    description: Supports system currency and regional settings, making it accessible and adaptable worldwide.
    fontawesome_icon_name: globe

  - title: Sync Across Devices
    description: Safely sync your financial data across multiple devices using iCloud for a seamless experience.
    fontawesome_icon_name: cloud-sync-alt

  - title: Enhanced Security
    description: Enable screen lock with Keychain Passcode, Touch ID, and Face ID to ensure that only you have access to your sensitive financial information.
    fontawesome_icon_name: lock

  - title: Rich Transaction Details
    description: Enhance transactions by adding images, locations, rich links, and more for a comprehensive financial narrative.
    fontawesome_icon_name: file-alt



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - any_additional_item 
  
collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
