#page title
page_title: Amigo - AI

# App Info
ios_app_id: 6450652473
ios_app_country: in

appstore_link: https://apps.apple.com/in/app/inout-expense-manager/id6450652473
playstore_link:
presskit_download_link:

app_icon: assets/appicon.png
app_name: Amigo - AI
app_price:
app_description: Embrace effortless finance management with Amigo - your AI-powered Expense Manager, guiding you towards smarter spending and saving.

enable_smart_app_banner: true

excerpt_separator: ""

# Information About Yourself
your_name: ♥
your_link: https://www.tirupatibalan.com
your_city:
email_address: tirupati@tirupatibalan.com
facebook_username:
instagram_username:
twitter_username:
github_username: tirupati17
youtube_username:
mastodon_link:

include: [".well-known"]

features:

  - title: Amigo, Your AI Companion
    description: Your financial buddy, Amigo, offers custom advice and insights, making money management feel like a breeze.
    fontawesome_icon_name: user-friends

  - title: Effortless Statement Sync
    description: Uploading bank statements is seamless, allowing Amigo to sort and analyze your finances for you.
    fontawesome_icon_name: file-import

  - title: Fluid Interface
    description: Navigate through your finances with ease, thanks to a clean and intuitive design.
    fontawesome_icon_name: compass

  - title: Trusted iCloud Security
    description: Rest easy knowing your data is encrypted and stored securely with iCloud, protected by biometric locks.
    fontawesome_icon_name: cloud

  - title: Insights at a Glance
    description: Visual reports turn complex data into understandable insights, helping you make informed decisions.
    fontawesome_icon_name: chart-pie

  - title: Organize Effortlessly
    description: Custom tags and categories mean tracking your transactions has never been easier or more personalized.
    fontawesome_icon_name: folder-open

  - title: Find in a Flash
    description: Powerful search capabilities let you pinpoint transactions instantly by various criteria.
    fontawesome_icon_name: search-plus

  - title: Globally Geared
    description: Amigo speaks your language, supporting various currencies and regional settings for universal use.
    fontawesome_icon_name: globe-americas

  - title: Unified Across Devices
    description: Keep your financial life in sync across devices with iCloud, ensuring access wherever you are.
    fontawesome_icon_name: sync-alt

  - title: Uncompromised Privacy
    description: Your financial data stays private with advanced security features, accessible only to you.
    fontawesome_icon_name: user-shield

  # - title: Rich Transaction Histories
  #   description: Transactions come to life with added details like images and locations, creating a fuller financial picture.
  #   fontawesome_icon_name: file-image

# Theme Settings - Dark Mode
topbar_color: "#252627"
topbar_transparency: 0.0
topbar_title_color: "#02040a"

cover_image: assets/headerimage.png
cover_overlay_color: "#ffffff"
cover_overlay_transparency: 1.0

device_color: black

body_background_color: "#ffffff"

link_color: "#007aff"

app_title_color: "#02040a"
app_price_color: "#02040a"
app_description_color: "#02040a"

feature_title_color: "#02040a"
feature_text_color: "#02040a"

feature_icons_foreground_color: "#02040a"
feature_icons_background_color: "#ffffff"

social_icons_foreground_color: "#02040a"
social_icons_background_color: "#ffffff"

footer_text_color: "#02040a"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed
  sass_dir: _sass

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - any_additional_item

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
